In [1]:
import pandas as pd 

df = pd.read_csv("/home/renile/Desktop/projects/Test/egypt_egg_prices_daily_2020_2026.csv")

df.head()

         Date Egg_Type  Min_Price  Max_Price  Avg_Price
0  2020-01-01    White      31.86      36.16      34.31
1  2020-01-01      Red      35.30      38.87      36.98
2  2020-01-01   Baladi      41.96      46.68      43.96
3  2020-01-02    White      34.68      37.84      35.76
4  2020-01-02      Red      36.73      40.82      38.07

In [3]:
df["Egg_Type"].value_counts()

Egg_Type
White     2304
Red       2304
Baladi    2304
Name: count, dtype: int64

In [4]:
df.shape

(6912, 5)

In [5]:
df.tail(5)

            Date Egg_Type  Min_Price  Max_Price  Avg_Price
6907  2026-04-21      Red      89.79      93.50      91.77
6908  2026-04-21   Baladi      95.47      99.73      97.43
6909  2026-04-22    White      87.15      92.21      89.81
6910  2026-04-22      Red      89.31      93.14      91.79
6911  2026-04-22   Baladi      97.92     101.38      99.98